[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
soon_staking = "66rNZNDufxtoJwGEFkQ9T6rm3P1Ex5Wd4V7MF6os1SVG"

[registry]
url = "https://anchor.projectserum.com"


[provider]
cluster = "https://rpc.testnet.soo.network/rpc"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
